In [1]:
import pandas as pd

students={
    "Name": ["rahul", "priya","aryan","sam","sima","ram"],
    "Age":[22,23,20,19,20,20],
    "Marks":[88,45,35,50,90,78]
}
df=pd.DataFrame(students)

In [2]:
df.head()

    Name  Age  Marks
0  rahul   22     88
1  priya   23     45
2  aryan   20     35
3    sam   19     50
4   sima   20     90

In [3]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   20.666667  64.333333
std     1.505545  23.855118
min    19.000000  35.000000
25%    20.000000  46.250000
50%    20.000000  64.000000
75%    21.500000  85.500000
max    23.000000  90.000000

In [4]:
df["Result"]=df["Marks"]>=50

In [5]:
import numpy as np

df["Result"] = np.where(df["Marks"] >= 50, "Pass", "Fail")
df

    Name  Age  Marks Result
0  rahul   22     88   Pass
1  priya   23     45   Fail
2  aryan   20     35   Fail
3    sam   19     50   Pass
4   sima   20     90   Pass
5    ram   20     78   Pass