In [21]:
import pandas as pd

students={
    "Name": ["rahul", "priya","aryan","sam","sima","sham","ram","ana"],
    "Age":[22,None,23,20,None,19,20,20],
    "Marks":[88,45,None,35,50,90,None,78]
}
df=pd.DataFrame(students)
df

    Name   Age  Marks
0  rahul  22.0   88.0
1  priya   NaN   45.0
2  aryan  23.0    NaN
3    sam  20.0   35.0
4   sima   NaN   50.0
5   sham  19.0   90.0
6    ram  20.0    NaN
7    ana  20.0   78.0

In [22]:
df.head()

    Name   Age  Marks
0  rahul  22.0   88.0
1  priya   NaN   45.0
2  aryan  23.0    NaN
3    sam  20.0   35.0
4   sima   NaN   50.0

In [23]:
df.shape

(8, 3)

In [24]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [25]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False
5  False  False  False
6  False  False   True
7  False  False  False

In [26]:
df.isnull().sum()

Name     0
Age      2
Marks    2
dtype: int64

In [27]:
df.dropna()

    Name   Age  Marks
0  rahul  22.0   88.0
3    sam  20.0   35.0
5   sham  19.0   90.0
7    ana  20.0   78.0

In [28]:
df["Marks"].mean()

64.33333333333333

In [29]:
df["Marks"].fillna(df["Marks"].mean())

0    88.000000
1    45.000000
2    64.333333
3    35.000000
4    50.000000
5    90.000000
6    64.333333
7    78.000000
Name: Marks, dtype: float64

In [30]:
df["Marks"]

0    88.0
1    45.0
2     NaN
3    35.0
4    50.0
5    90.0
6     NaN
7    78.0
Name: Marks, dtype: float64

In [31]:
df["Marks"]>70

0     True
1    False
2    False
3    False
4    False
5     True
6    False
7     True
Name: Marks, dtype: bool

In [32]:
df[df["Marks"]>70]

    Name   Age  Marks
0  rahul  22.0   88.0
5   sham  19.0   90.0
7    ana  20.0   78.0

In [33]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   20.666667  64.333333
std     1.505545  23.855118
min    19.000000  35.000000
25%    20.000000  46.250000
50%    20.000000  64.000000
75%    21.500000  85.500000
max    23.000000  90.000000